language: bash

services:
  - docker

# Only clone the most recent commit.
git:
  depth: 1

script:
  - >-
    docker run -it --rm -v $(pwd)/charts:/charts
    --entrypoint /bin/sh linkyard/docker-helm
    -c "helm lint /charts/*"
