apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "beacon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "beacon.name" . }}
    helm.sh/chart: {{ include "beacon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "beacon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "beacon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: BEACON_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "beacon.fullname" . }}
                  key: url
            - name: BEACON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "beacon.fullname" . }}
                  key: key
            - name: BEACON_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "beacon.fullname" . }}
                  key: interval
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
