{{ if .Values.Gossip.Create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "beacon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "beacon.name" . }}
    helm.sh/chart: {{ include "beacon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  key: {{ .Values.key | b64enc }}
