# Default values.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

replicaCount: 1
progressDeadlineSeconds: 600
revisionHistoryLimit: 10
loadBalancerIP: 192.168.88.50

strategy:
  rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate

image:
  repository: coredns/coredns
  tag: 1.3.1
  pullPolicy: IfNotPresent

livenessProbe:
  failureThreshold: 5
  httpGet:
    path: /health
    port: 8080
    scheme: HTTP
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    add:
    - NET_BIND_SERVICE
    drop:
    - all
  procMount: Default
  readOnlyRootFilesystem: true

resources:
  limits:
    memory: 170Mi
  requests:
    cpu: 100m
    memory: 70Mi
