kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "_.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "_.name" . }}
    helm.sh/chart: {{ include "_.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi

