{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version| replace "+" "_" }}"
    heritage: {{ .Release.Service }}
  annotations:
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - {{ template "hostname" .Values.service.url }}
    secretName: {{ .Values.ingress.tlsName }}
  rules:
  - host: {{ template "hostname" .Values.service.url }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "appname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end -}}
